#!/bin/sh

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

IFS=' '
while read local_ref local_sha remote_ref remote_sha
do
	if [ "$local_sha" = $z40 ]
	then
		# Handle delete
	else
		if [ "$remote_sha" = $z40 ]
		then
			# New branch, examine all commits
			range="$local_sha"
		else
			# Update to existing branch, examine new commits
			range="$remote_sha..$local_sha"
		fi

		# Check for WIP commit
		commit=`git rev-list -n 1 --grep '^WIP' "$range"`
		if [ -n "$commit" ]
		then
			echo "Found WIP commit in $local_ref, not pushing"
			exit 1
		fi
	fi
done

# Run clippy
if ! cargo clippy --workspace --locked -- -D warnings; then
    cat <<EOF
Error: Clippy exited with errors.
EOF
    exit 1
fi

# Run tests
if ! cargo test --workspace; then
    cat <<EOF
Error: Tests exited with errors.
EOF
    exit 1
fi
